service: jcr-contact-api
tenant: mflamb
app: jcr-serverless-contact-form
plugins:
  - serverless-pseudo-parameters
custom:
  secrets: ${file(secrets.json)}
  JCRLambdaName: ${self:service}-website-contact-form-${self:provider.stage}
provider:
  name: aws
  runtime: nodejs10.x
  profile: ${opt:profile, "jcr-aws"}
  region: ${opt:region, "us-east-1"}
  stage: ${opt:stage, "dev"}
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    EMAIL: ${self:custom.secrets.EMAIL}
    DOMAIN: ${self:custom.secrets.DOMAIN}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "arn:aws:ses:${self:provider.region}:#{AWS::AccountId}:identity/${self:custom.secrets.EMAIL}"
functions:
  send:
    handler: emailJim.send
    events:
      - http:
          path: email/send
          method: POST
          cors: true
